### ISSUE TITLE
just a nitpick of styling

### ISSUE THREAD

**Issue by lopste** [Autofirejm/autofirejm.github.io#1]
I'm just looking at source of the website, here's a recommendation: You should use .css files for styling.
You can put it in using
`<link href="filename.css" rel="stylesheet"` and it's very easy to edit it (and switch light/dark mode). it also does give some extra features, like animation (see [my website's style](https://lopste.github.io/style.css))

**Comment by Autofirejm** [comment]
You've been invited to the repository to help with this, as i have trouble with CSS files
