### ISSUE TITLE
Specify class in style.css

### ISSUE THREAD

**Issue by ILOVETOMAKESTUFF** [Autofirejm/autofirejm.github.io#5]
I think I might've spotted a link, or maybe you are still coding it, but I couldn't find the classes `.Main-Begin` and `.Gitlink`. I think you should add some code in the `style.css` file. 
`<p class="Main-Begin">...</p>`
 `<a class="GitLink" href="https://github.com/Autofirejm/autofirejm.github.io"> github repository</a>`

**Comment by Autofirejm** [comment]
er yes-  it is a link that will be coded in CSS later it's for this exact repo
